smallLike = 10000 # 抓取最小视频赞数,仅抓取大于此值的视频
isDownload = 1 # 是否下载远程 用户头像 封面图 视频 到本地  0否1是

[gin]
addr = 8080 #设置gin listen 端口
model = "release" # 设置gin模式 release debug test

[app]
packageName = "com.ss.android.ugc.aweme" # 抖音app包名
startPath = ".main.MainActivity" # 抖音app包首页path
restart = 60 # 重新打开时间  单位秒
sleep = 60 # 重新打开睡眠时间  单位秒

# 搜索模块
[search]
keyword = ["昆明","云南"] #搜索关键词
openX = 1000 # 首页搜索页面进口
openY = 150
inputX = 300 # 搜索框输入口
inputY = 150
clearX = 840 # 搜索框清空按钮
clearY = 150
searchX = 980 # 搜索页面 搜索按钮
searchY = 150

[swipe]
# 滑动 开始和结束 像素坐标值
startX = 500
startY = 1000
endX = 489
endY = 123
sleep = 200 # 滑动等待时间  单位毫秒
